with gestor as (
    select
        try_cast("NU_ANO_CENSO" as integer) as ano,
        cast("CO_ENTIDADE" as varchar) as id_escola,
        try_cast("QT_GEST_BAS" as integer) as qt_gest_bas,
        try_cast("QT_GEST_BAS_FEM" as integer) as qt_gest_bas_fem,
        try_cast("QT_GEST_BAS_MASC" as integer) as qt_gest_bas_masc,
        try_cast("QT_GEST_BAS_BRANCA" as integer) as qt_gest_bas_branca,
        try_cast("QT_GEST_BAS_PRETA" as integer) as qt_gest_bas_preta,
        try_cast("QT_GEST_BAS_PARDA" as integer) as qt_gest_bas_parda,
        try_cast("QT_GEST_BAS_30_39" as integer) as qt_gest_bas_30_39,
        try_cast("QT_GEST_BAS_40_49" as integer) as qt_gest_bas_40_49,
        try_cast("QT_GEST_BAS_50_54" as integer) as qt_gest_bas_50_54,
        try_cast("QT_GEST_BAS_55_59" as integer) as qt_gest_bas_55_59,
        try_cast("QT_GEST_BAS_60_MAIS" as integer) as qt_gest_bas_60_mais,
        try_cast("QT_GEST_BAS_PCD" as integer) as qt_gest_bas_pcd,
        try_cast("QT_GEST_BAS_ESCO_EM" as integer) as qt_gest_bas_esco_em,
        try_cast("QT_GEST_BAS_ESCO_SUP_GRAD_LICEN" as integer) as qt_gest_bas_esco_sup_grad_licen,
        try_cast("QT_GEST_BAS_ESCO_SUP_POS_ESPEC" as integer) as qt_gest_bas_esco_sup_pos_espec,
        try_cast("QT_GEST_BAS_ESCO_SUP_POS_MESTRA" as integer) as qt_gest_bas_esco_sup_pos_mestra,
        try_cast("QT_GEST_BAS_ESCO_SUP_POS_DOUTO" as integer) as qt_gest_bas_esco_sup_pos_douto,
        try_cast("QT_GEST_BAS_VINCULO_CONCUR" as integer) as qt_gest_bas_vinculo_concur,
        try_cast("QT_GEST_BAS_VINCULO_CONTRA" as integer) as qt_gest_bas_vinculo_contra,
        try_cast("QT_GEST_BAS_VINCULO_CLT" as integer) as qt_gest_bas_vinculo_clt,
        try_cast("QT_GEST_BAS_DIRETOR" as integer) as qt_gest_bas_diretor,
        try_cast("QT_GEST_BAS_OUTRO" as integer) as qt_gest_bas_outro,
        try_cast("QT_GEST_BAS_ACESSO_CARGO_INDIC" as integer) as qt_gest_bas_acesso_cargo_indic,
        try_cast("QT_GEST_BAS_ACESSO_CARGO_SEL" as integer) as qt_gest_bas_acesso_cargo_sel,
        try_cast("QT_GEST_BAS_ACESSO_CARGO_CONC" as integer) as qt_gest_bas_acesso_cargo_conc,
        try_cast("QT_GEST_BAS_ACESSO_CARGO_ELEIC" as integer) as qt_gest_bas_acesso_cargo_eleic,
        try_cast("QT_GEST_BAS_ESPEC_ENS_MEDIO" as integer) as qt_gest_bas_espec_ens_medio,
        try_cast("QT_GEST_BAS_ESPEC_GESTAO" as integer) as qt_gest_bas_espec_gestao
    from read_csv(
        'data/raw/censo_escolar_2025/Tabela_Gestor_Escolar_2025.csv.gz',
        delim=';',
        header=true,
        all_varchar=true,
        ignore_errors=true
    )
)

select
    gestor.ano,
    escola.co_uf,
    escola.sg_uf,
    escola.id_municipio,
    escola.id_escola,
    escola.tp_dependencia,
    escola.tp_localizacao,
    gestor.qt_gest_bas,
    gestor.qt_gest_bas_fem,
    gestor.qt_gest_bas_masc,
    gestor.qt_gest_bas_branca,
    gestor.qt_gest_bas_preta,
    gestor.qt_gest_bas_parda,
    gestor.qt_gest_bas_30_39,
    gestor.qt_gest_bas_40_49,
    gestor.qt_gest_bas_50_54,
    gestor.qt_gest_bas_55_59,
    gestor.qt_gest_bas_60_mais,
    gestor.qt_gest_bas_pcd,
    gestor.qt_gest_bas_esco_em,
    gestor.qt_gest_bas_esco_sup_grad_licen,
    gestor.qt_gest_bas_esco_sup_pos_espec,
    gestor.qt_gest_bas_esco_sup_pos_mestra,
    gestor.qt_gest_bas_esco_sup_pos_douto,
    gestor.qt_gest_bas_vinculo_concur,
    gestor.qt_gest_bas_vinculo_contra,
    gestor.qt_gest_bas_vinculo_clt,
    gestor.qt_gest_bas_diretor,
    gestor.qt_gest_bas_outro,
    gestor.qt_gest_bas_acesso_cargo_indic,
    gestor.qt_gest_bas_acesso_cargo_sel,
    gestor.qt_gest_bas_acesso_cargo_conc,
    gestor.qt_gest_bas_acesso_cargo_eleic,
    gestor.qt_gest_bas_espec_ens_medio,
    gestor.qt_gest_bas_espec_gestao
from gestor
left join {{ ref('stg_censo_escolar_2025_escola') }} as escola
    on gestor.ano = escola.ano
   and gestor.id_escola = escola.id_escola
