{{ config(materialized='table') }}

select
    ano,
    id_municipio,
    sg_uf,
    no_uf,
    no_municipio,
    periodo_nem,
    qt_escolas,
    qt_escolas_em,
    tem_historico_tecnico_no_ano,
    qt_escolas_com_curso_tecnico,
    qt_cursos_tecnicos_distintos,
    qt_areas_tecnicas_distintas,
    qt_curso_tec,
    qt_mat_curso_tec,
    qt_curso_tec_ct,
    qt_mat_curso_tec_ct,
    qt_curso_tec_nm,
    qt_mat_curso_tec_nm,
    qt_curso_tec_conc,
    qt_mat_curso_tec_conc,
    qt_curso_tec_subs,
    qt_mat_curso_tec_subs,
    qt_curso_tec_eja,
    qt_mat_curso_tec_eja,
    qt_curso_tec_iftp,
    qt_mat_curso_tec_iftp,
    qt_curso_tec_iftp_ct,
    qt_mat_curso_tec_iftp_ct,
    prop_escolas_com_curso_tecnico,
    prop_escolas_em_com_curso_tecnico,
    case when coalesce(qt_escolas, 0) > 0 then qt_escolas_com_curso_tecnico * 1.0 / qt_escolas else null end as escolas_com_tecnico_por_total_escolas,
    case when coalesce(qt_escolas_em, 0) > 0 then qt_escolas_com_curso_tecnico * 1.0 / qt_escolas_em else null end as escolas_com_tecnico_por_escolas_em,
    case when coalesce(qt_escolas_com_curso_tecnico, 0) > 0 then qt_mat_curso_tec * 1.0 / qt_escolas_com_curso_tecnico else null end as matriculas_tecnicas_por_escola_com_tecnico,
    case when coalesce(qt_escolas, 0) > 0 then qt_mat_curso_tec * 1.0 / qt_escolas else null end as matriculas_tecnicas_por_escola_total,
    case when coalesce(qt_escolas_com_curso_tecnico, 0) > 0 then qt_cursos_tecnicos_distintos * 1.0 / qt_escolas_com_curso_tecnico else null end as cursos_tecnicos_distintos_por_escola_com_tecnico
from {{ ref('int_municipio_ano_tecnico') }}
