{{ config(materialized='table') }}

with escola as (
    select *
    from {{ ref('int_censo_escola_ano_2019_2025') }}
),
municipio as (
    select
        ano,
        id_municipio,
        nome_municipio,
        id_uf,
        sigla_uf,
        nome_uf,
        nome_regiao,
        capital_uf,
        amazonia_legal,
        pib,
        tem_pib_no_ano,
        populacao,
        taxa_alfabetizacao,
        taxa_alfabetizacao_detalhada_calculada,
        ano_saeb_referencia,
        tem_saeb_no_ano_flag,
        media_12_lp,
        media_12_mt,
        media_12_lp_mt,
        delta_media_12_lp,
        delta_media_12_mt,
        delta_media_12_lp_mt
    from {{ ref('int_municipio_ano_painel_educacional') }}
)

select
    escola.ano,
    escola.id_municipio,
    municipio.nome_municipio,
    municipio.id_uf,
    municipio.sigla_uf,
    municipio.nome_uf,
    municipio.nome_regiao,
    municipio.capital_uf,
    municipio.amazonia_legal,
    escola.no_entidade,
    escola.id_escola,
    escola.tp_dependencia,
    escola.tp_localizacao,
    escola.fonte_censo,
    escola.periodo_nem,
    escola.ordem_periodo_nem,
    escola.in_bas,
    escola.in_inf,
    escola.in_fund,
    escola.in_med,
    escola.in_med_padronizado,
    escola.in_prof,
    escola.in_prof_tec,
    escola.in_eja,
    escola.in_regular,
    escola.in_profissionalizante,
    escola.tp_itinerario_formativo,
    escola.in_itinerario_aprofundamento,
    escola.in_itinerario_tecn_prof,
    escola.in_mediacao_presencial,
    escola.in_mediacao_semipresencial,
    escola.in_mediacao_ead,
    escola.in_biblioteca,
    escola.in_biblioteca_sala_leitura,
    escola.in_internet,
    escola.in_internet_aprendizagem,
    escola.in_laboratorio_ciencias,
    escola.in_laboratorio_informatica,
    escola.in_laboratorio_educ_prof,
    escola.in_sala_oficinas_educ_prof,
    escola.in_quadra_esportes,
    escola.qt_salas_utilizadas,
    escola.qt_mat_med_compat,
    escola.qt_mat_med_int_compat,
    escola.qt_mat_med_prop,
    escola.qt_mat_med_nm,
    escola.qt_mat_med_ifa,
    escola.qt_mat_med_ifa_ling,
    escola.qt_mat_med_ifa_mate,
    escola.qt_mat_med_ifa_cienc,
    escola.qt_mat_med_ifa_huma,
    escola.qt_mat_med_iftp_ct,
    escola.qt_mat_med_iftp_qp,
    escola.qt_mat_med_arti_iftp_ct,
    escola.qt_mat_med_arti_iftp_qp,
    escola.qt_mat_prof_tec_compat,
    escola.qt_mat_prof_tec,
    escola.qt_mat_prof,
    escola.qt_mat_prof_int,
    escola.qt_mat_prof_tec_int,
    escola.qt_tur_med_compat,
    escola.qt_tur_med_int_compat,
    escola.qt_tur_med_prop,
    escola.qt_tur_med_nm,
    escola.qt_tur_med_ifa,
    escola.qt_tur_med_iftp_ct,
    escola.qt_tur_med_iftp_qp,
    escola.qt_tur_prof_tec,
    escola.qt_doc_med_compat,
    escola.qt_doc_med,
    escola.qt_doc_prof_tec,
    escola.qt_doc_bas_disc_projeto_de_vida,
    escola.qt_doc_bas_disc_profissiona,
    escola.qt_doc_bas_disc_info_computacao,
    escola.qt_gest_bas,
    escola.qt_gest_bas_espec_ens_medio,
    case when coalesce(escola.qt_mat_med_compat, 0) > 0 then escola.qt_mat_med_int_compat * 1.0 / escola.qt_mat_med_compat else null end as prop_mat_em_integral_escola,
    case when coalesce(escola.qt_mat_med_compat, 0) > 0 then escola.qt_mat_prof_tec_compat * 1.0 / escola.qt_mat_med_compat else null end as prop_mat_em_tecnico_profissional_escola,
    case when coalesce(escola.qt_tur_med_compat, 0) > 0 then escola.qt_tur_med_int_compat * 1.0 / escola.qt_tur_med_compat else null end as prop_tur_em_integral_escola,
    case when coalesce(escola.qt_doc_med_compat, 0) > 0 then escola.qt_doc_prof_tec * 1.0 / escola.qt_doc_med_compat else null end as prop_doc_em_prof_tec_escola,
    municipio.ano_saeb_referencia,
    municipio.tem_saeb_no_ano_flag,
    municipio.pib,
    municipio.tem_pib_no_ano,
    municipio.populacao,
    municipio.taxa_alfabetizacao,
    municipio.taxa_alfabetizacao_detalhada_calculada,
    municipio.media_12_lp,
    municipio.media_12_mt,
    municipio.media_12_lp_mt,
    municipio.delta_media_12_lp,
    municipio.delta_media_12_mt,
    municipio.delta_media_12_lp_mt
from escola
left join municipio
    on escola.ano = municipio.ano
   and escola.id_municipio = municipio.id_municipio
