with saeb_2019 as (
    select
        2019::integer as ano_saeb,
        '2019' as ano_fonte,
        cast("CO_UF" as varchar) as co_uf,
        cast("NO_UF" as varchar) as no_uf,
        cast("CO_MUNICIPIO" as varchar) as id_municipio,
        cast("NO_MUNICIPIO" as varchar) as no_municipio,
        cast("DEPENDENCIA_ADM" as varchar) as dependencia_adm,
        cast("LOCALIZACAO" as varchar) as localizacao,
        try_cast("MEDIA_5_LP" as double) as media_5_lp,
        try_cast("MEDIA_5_MT" as double) as media_5_mt,
        try_cast("MEDIA_9_LP" as double) as media_9_lp,
        try_cast("MEDIA_9_MT" as double) as media_9_mt,
        try_cast("MEDIA_12_LP" as double) as media_12_lp,
        try_cast("MEDIA_12_MT" as double) as media_12_mt,
        try_cast("nivel_0_LP5" as double) as nivel_0_lp5,
        try_cast("nivel_1_LP5" as double) as nivel_1_lp5,
        try_cast("nivel_2_LP5" as double) as nivel_2_lp5,
        try_cast("nivel_3_LP5" as double) as nivel_3_lp5,
        try_cast("nivel_4_LP5" as double) as nivel_4_lp5,
        try_cast("nivel_5_LP5" as double) as nivel_5_lp5,
        try_cast("nivel_6_LP5" as double) as nivel_6_lp5,
        try_cast("nivel_7_LP5" as double) as nivel_7_lp5,
        try_cast("nivel_8_LP5" as double) as nivel_8_lp5,
        try_cast("nivel_9_LP5" as double) as nivel_9_lp5,
        try_cast("nivel_0_MT5" as double) as nivel_0_mt5,
        try_cast("nivel_1_MT5" as double) as nivel_1_mt5,
        try_cast("nivel_2_MT5" as double) as nivel_2_mt5,
        try_cast("nivel_3_MT5" as double) as nivel_3_mt5,
        try_cast("nivel_4_MT5" as double) as nivel_4_mt5,
        try_cast("nivel_5_MT5" as double) as nivel_5_mt5,
        try_cast("nivel_6_MT5" as double) as nivel_6_mt5,
        try_cast("nivel_7_MT5" as double) as nivel_7_mt5,
        try_cast("nivel_8_MT5" as double) as nivel_8_mt5,
        try_cast("nivel_9_MT5" as double) as nivel_9_mt5,
        try_cast("nivel_10_MT5" as double) as nivel_10_mt5,
        try_cast("nivel_0_LP9" as double) as nivel_0_lp9,
        try_cast("nivel_1_LP9" as double) as nivel_1_lp9,
        try_cast("nivel_2_LP9" as double) as nivel_2_lp9,
        try_cast("nivel_3_LP9" as double) as nivel_3_lp9,
        try_cast("nivel_4_LP9" as double) as nivel_4_lp9,
        try_cast("nivel_5_LP9" as double) as nivel_5_lp9,
        try_cast("nivel_6_LP9" as double) as nivel_6_lp9,
        try_cast("nivel_7_LP9" as double) as nivel_7_lp9,
        try_cast("nivel_8_LP9" as double) as nivel_8_lp9,
        try_cast("nivel_0_MT9" as double) as nivel_0_mt9,
        try_cast("nivel_1_MT9" as double) as nivel_1_mt9,
        try_cast("nivel_2_MT9" as double) as nivel_2_mt9,
        try_cast("nivel_3_MT9" as double) as nivel_3_mt9,
        try_cast("nivel_4_MT9" as double) as nivel_4_mt9,
        try_cast("nivel_5_MT9" as double) as nivel_5_mt9,
        try_cast("nivel_6_MT9" as double) as nivel_6_mt9,
        try_cast("nivel_7_MT9" as double) as nivel_7_mt9,
        try_cast("nivel_8_MT9" as double) as nivel_8_mt9,
        try_cast("nivel_9_MT9" as double) as nivel_9_mt9,
        try_cast("nivel_0_LP12" as double) as nivel_0_lp12,
        try_cast("nivel_1_LP12" as double) as nivel_1_lp12,
        try_cast("nivel_2_LP12" as double) as nivel_2_lp12,
        try_cast("nivel_3_LP12" as double) as nivel_3_lp12,
        try_cast("nivel_4_LP12" as double) as nivel_4_lp12,
        try_cast("nivel_5_LP12" as double) as nivel_5_lp12,
        try_cast("nivel_6_LP12" as double) as nivel_6_lp12,
        try_cast("nivel_7_LP12" as double) as nivel_7_lp12,
        try_cast("nivel_8_LP12" as double) as nivel_8_lp12,
        try_cast("nivel_0_MT12" as double) as nivel_0_mt12,
        try_cast("nivel_1_MT12" as double) as nivel_1_mt12,
        try_cast("nivel_2_MT12" as double) as nivel_2_mt12,
        try_cast("nivel_3_MT12" as double) as nivel_3_mt12,
        try_cast("nivel_4_MT12" as double) as nivel_4_mt12,
        try_cast("nivel_5_MT12" as double) as nivel_5_mt12,
        try_cast("nivel_6_MT12" as double) as nivel_6_mt12,
        try_cast("nivel_7_MT12" as double) as nivel_7_mt12,
        try_cast("nivel_8_MT12" as double) as nivel_8_mt12,
        try_cast("nivel_9_MT12" as double) as nivel_9_mt12,
        try_cast("nivel_10_MT12" as double) as nivel_10_mt12,
        null::double as nivel_0_lp13,
        null::double as nivel_1_lp13,
        null::double as nivel_2_lp13,
        null::double as nivel_3_lp13,
        null::double as nivel_4_lp13,
        null::double as nivel_5_lp13,
        null::double as nivel_6_lp13,
        null::double as nivel_7_lp13,
        null::double as nivel_8_lp13,
        null::double as nivel_0_mt13,
        null::double as nivel_1_mt13,
        null::double as nivel_2_mt13,
        null::double as nivel_3_mt13,
        null::double as nivel_4_mt13,
        null::double as nivel_5_mt13,
        null::double as nivel_6_mt13,
        null::double as nivel_7_mt13,
        null::double as nivel_8_mt13,
        null::double as nivel_9_mt13,
        null::double as nivel_10_mt13,
        null::double as nivel_0_lp14,
        null::double as nivel_1_lp14,
        null::double as nivel_2_lp14,
        null::double as nivel_3_lp14,
        null::double as nivel_4_lp14,
        null::double as nivel_5_lp14,
        null::double as nivel_6_lp14,
        null::double as nivel_7_lp14,
        null::double as nivel_8_lp14,
        null::double as nivel_0_mt14,
        null::double as nivel_1_mt14,
        null::double as nivel_2_mt14,
        null::double as nivel_3_mt14,
        null::double as nivel_4_mt14,
        null::double as nivel_5_mt14,
        null::double as nivel_6_mt14,
        null::double as nivel_7_mt14,
        null::double as nivel_8_mt14,
        null::double as nivel_9_mt14,
        null::double as nivel_10_mt14
    from {{ source('raw_saeb_2019', 'saeb_resultados_municipios_2019') }}
),

saeb_2021_2023 as (
    select
        try_cast("ANO_SAEB" as integer) as ano_saeb,
        cast(try_cast("ANO_SAEB" as integer) as varchar) as ano_fonte,
        cast("CO_UF" as varchar) as co_uf,
        cast("NO_UF" as varchar) as no_uf,
        cast("CO_MUNICIPIO" as varchar) as id_municipio,
        cast("NO_MUNICIPIO" as varchar) as no_municipio,
        cast("DEPENDENCIA_ADM" as varchar) as dependencia_adm,
        cast("LOCALIZACAO" as varchar) as localizacao,
        try_cast("MEDIA_5_LP" as double) as media_5_lp,
        try_cast("MEDIA_5_MT" as double) as media_5_mt,
        try_cast("MEDIA_9_LP" as double) as media_9_lp,
        try_cast("MEDIA_9_MT" as double) as media_9_mt,
        try_cast("MEDIA_12_LP" as double) as media_12_lp,
        try_cast("MEDIA_12_MT" as double) as media_12_mt,
        try_cast("nivel_0_LP5" as double) as nivel_0_lp5,
        try_cast("nivel_1_LP5" as double) as nivel_1_lp5,
        try_cast("nivel_2_LP5" as double) as nivel_2_lp5,
        try_cast("nivel_3_LP5" as double) as nivel_3_lp5,
        try_cast("nivel_4_LP5" as double) as nivel_4_lp5,
        try_cast("nivel_5_LP5" as double) as nivel_5_lp5,
        try_cast("nivel_6_LP5" as double) as nivel_6_lp5,
        try_cast("nivel_7_LP5" as double) as nivel_7_lp5,
        try_cast("nivel_8_LP5" as double) as nivel_8_lp5,
        try_cast("nivel_9_LP5" as double) as nivel_9_lp5,
        try_cast("nivel_0_MT5" as double) as nivel_0_mt5,
        try_cast("nivel_1_MT5" as double) as nivel_1_mt5,
        try_cast("nivel_2_MT5" as double) as nivel_2_mt5,
        try_cast("nivel_3_MT5" as double) as nivel_3_mt5,
        try_cast("nivel_4_MT5" as double) as nivel_4_mt5,
        try_cast("nivel_5_MT5" as double) as nivel_5_mt5,
        try_cast("nivel_6_MT5" as double) as nivel_6_mt5,
        try_cast("nivel_7_MT5" as double) as nivel_7_mt5,
        try_cast("nivel_8_MT5" as double) as nivel_8_mt5,
        try_cast("nivel_9_MT5" as double) as nivel_9_mt5,
        try_cast("nivel_10_MT5" as double) as nivel_10_mt5,
        try_cast("nivel_0_LP9" as double) as nivel_0_lp9,
        try_cast("nivel_1_LP9" as double) as nivel_1_lp9,
        try_cast("nivel_2_LP9" as double) as nivel_2_lp9,
        try_cast("nivel_3_LP9" as double) as nivel_3_lp9,
        try_cast("nivel_4_LP9" as double) as nivel_4_lp9,
        try_cast("nivel_5_LP9" as double) as nivel_5_lp9,
        try_cast("nivel_6_LP9" as double) as nivel_6_lp9,
        try_cast("nivel_7_LP9" as double) as nivel_7_lp9,
        try_cast("nivel_8_LP9" as double) as nivel_8_lp9,
        try_cast("nivel_0_MT9" as double) as nivel_0_mt9,
        try_cast("nivel_1_MT9" as double) as nivel_1_mt9,
        try_cast("nivel_2_MT9" as double) as nivel_2_mt9,
        try_cast("nivel_3_MT9" as double) as nivel_3_mt9,
        try_cast("nivel_4_MT9" as double) as nivel_4_mt9,
        try_cast("nivel_5_MT9" as double) as nivel_5_mt9,
        try_cast("nivel_6_MT9" as double) as nivel_6_mt9,
        try_cast("nivel_7_MT9" as double) as nivel_7_mt9,
        try_cast("nivel_8_MT9" as double) as nivel_8_mt9,
        try_cast("nivel_9_MT9" as double) as nivel_9_mt9,
        try_cast("nivel_0_LP12" as double) as nivel_0_lp12,
        try_cast("nivel_1_LP12" as double) as nivel_1_lp12,
        try_cast("nivel_2_LP12" as double) as nivel_2_lp12,
        try_cast("nivel_3_LP12" as double) as nivel_3_lp12,
        try_cast("nivel_4_LP12" as double) as nivel_4_lp12,
        try_cast("nivel_5_LP12" as double) as nivel_5_lp12,
        try_cast("nivel_6_LP12" as double) as nivel_6_lp12,
        try_cast("nivel_7_LP12" as double) as nivel_7_lp12,
        try_cast("nivel_8_LP12" as double) as nivel_8_lp12,
        try_cast("nivel_0_MT12" as double) as nivel_0_mt12,
        try_cast("nivel_1_MT12" as double) as nivel_1_mt12,
        try_cast("nivel_2_MT12" as double) as nivel_2_mt12,
        try_cast("nivel_3_MT12" as double) as nivel_3_mt12,
        try_cast("nivel_4_MT12" as double) as nivel_4_mt12,
        try_cast("nivel_5_MT12" as double) as nivel_5_mt12,
        try_cast("nivel_6_MT12" as double) as nivel_6_mt12,
        try_cast("nivel_7_MT12" as double) as nivel_7_mt12,
        try_cast("nivel_8_MT12" as double) as nivel_8_mt12,
        try_cast("nivel_9_MT12" as double) as nivel_9_mt12,
        try_cast("nivel_10_MT12" as double) as nivel_10_mt12,
        try_cast("nivel_0_LP13" as double) as nivel_0_lp13,
        try_cast("nivel_1_LP13" as double) as nivel_1_lp13,
        try_cast("nivel_2_LP13" as double) as nivel_2_lp13,
        try_cast("nivel_3_LP13" as double) as nivel_3_lp13,
        try_cast("nivel_4_LP13" as double) as nivel_4_lp13,
        try_cast("nivel_5_LP13" as double) as nivel_5_lp13,
        try_cast("nivel_6_LP13" as double) as nivel_6_lp13,
        try_cast("nivel_7_LP13" as double) as nivel_7_lp13,
        try_cast("nivel_8_LP13" as double) as nivel_8_lp13,
        try_cast("nivel_0_MT13" as double) as nivel_0_mt13,
        try_cast("nivel_1_MT13" as double) as nivel_1_mt13,
        try_cast("nivel_2_MT13" as double) as nivel_2_mt13,
        try_cast("nivel_3_MT13" as double) as nivel_3_mt13,
        try_cast("nivel_4_MT13" as double) as nivel_4_mt13,
        try_cast("nivel_5_MT13" as double) as nivel_5_mt13,
        try_cast("nivel_6_MT13" as double) as nivel_6_mt13,
        try_cast("nivel_7_MT13" as double) as nivel_7_mt13,
        try_cast("nivel_8_MT13" as double) as nivel_8_mt13,
        try_cast("nivel_9_MT13" as double) as nivel_9_mt13,
        try_cast("nivel_10_MT13" as double) as nivel_10_mt13,
        try_cast("nivel_0_LP14" as double) as nivel_0_lp14,
        try_cast("nivel_1_LP14" as double) as nivel_1_lp14,
        try_cast("nivel_2_LP14" as double) as nivel_2_lp14,
        try_cast("nivel_3_LP14" as double) as nivel_3_lp14,
        try_cast("nivel_4_LP14" as double) as nivel_4_lp14,
        try_cast("nivel_5_LP14" as double) as nivel_5_lp14,
        try_cast("nivel_6_LP14" as double) as nivel_6_lp14,
        try_cast("nivel_7_LP14" as double) as nivel_7_lp14,
        try_cast("nivel_8_LP14" as double) as nivel_8_lp14,
        try_cast("nivel_0_MT14" as double) as nivel_0_mt14,
        try_cast("nivel_1_MT14" as double) as nivel_1_mt14,
        try_cast("nivel_2_MT14" as double) as nivel_2_mt14,
        try_cast("nivel_3_MT14" as double) as nivel_3_mt14,
        try_cast("nivel_4_MT14" as double) as nivel_4_mt14,
        try_cast("nivel_5_MT14" as double) as nivel_5_mt14,
        try_cast("nivel_6_MT14" as double) as nivel_6_mt14,
        try_cast("nivel_7_MT14" as double) as nivel_7_mt14,
        try_cast("nivel_8_MT14" as double) as nivel_8_mt14,
        try_cast("nivel_9_MT14" as double) as nivel_9_mt14,
        try_cast("nivel_10_MT14" as double) as nivel_10_mt14
    from {{ source('raw_saeb_2021', 'saeb_resultados_municipios_2021') }}
    where try_cast("ANO_SAEB" as integer) = 2021

    union all

    select
        try_cast("ANO_SAEB" as integer) as ano_saeb,
        cast(try_cast("ANO_SAEB" as integer) as varchar) as ano_fonte,
        cast("CO_UF" as varchar) as co_uf,
        cast("NO_UF" as varchar) as no_uf,
        cast("CO_MUNICIPIO" as varchar) as id_municipio,
        cast("NO_MUNICIPIO" as varchar) as no_municipio,
        cast("DEPENDENCIA_ADM" as varchar) as dependencia_adm,
        cast("LOCALIZACAO" as varchar) as localizacao,
        try_cast("MEDIA_5_LP" as double) as media_5_lp,
        try_cast("MEDIA_5_MT" as double) as media_5_mt,
        try_cast("MEDIA_9_LP" as double) as media_9_lp,
        try_cast("MEDIA_9_MT" as double) as media_9_mt,
        try_cast("MEDIA_12_LP" as double) as media_12_lp,
        try_cast("MEDIA_12_MT" as double) as media_12_mt,
        try_cast("nivel_0_LP5" as double) as nivel_0_lp5,
        try_cast("nivel_1_LP5" as double) as nivel_1_lp5,
        try_cast("nivel_2_LP5" as double) as nivel_2_lp5,
        try_cast("nivel_3_LP5" as double) as nivel_3_lp5,
        try_cast("nivel_4_LP5" as double) as nivel_4_lp5,
        try_cast("nivel_5_LP5" as double) as nivel_5_lp5,
        try_cast("nivel_6_LP5" as double) as nivel_6_lp5,
        try_cast("nivel_7_LP5" as double) as nivel_7_lp5,
        try_cast("nivel_8_LP5" as double) as nivel_8_lp5,
        try_cast("nivel_9_LP5" as double) as nivel_9_lp5,
        try_cast("nivel_0_MT5" as double) as nivel_0_mt5,
        try_cast("nivel_1_MT5" as double) as nivel_1_mt5,
        try_cast("nivel_2_MT5" as double) as nivel_2_mt5,
        try_cast("nivel_3_MT5" as double) as nivel_3_mt5,
        try_cast("nivel_4_MT5" as double) as nivel_4_mt5,
        try_cast("nivel_5_MT5" as double) as nivel_5_mt5,
        try_cast("nivel_6_MT5" as double) as nivel_6_mt5,
        try_cast("nivel_7_MT5" as double) as nivel_7_mt5,
        try_cast("nivel_8_MT5" as double) as nivel_8_mt5,
        try_cast("nivel_9_MT5" as double) as nivel_9_mt5,
        try_cast("nivel_10_MT5" as double) as nivel_10_mt5,
        try_cast("nivel_0_LP9" as double) as nivel_0_lp9,
        try_cast("nivel_1_LP9" as double) as nivel_1_lp9,
        try_cast("nivel_2_LP9" as double) as nivel_2_lp9,
        try_cast("nivel_3_LP9" as double) as nivel_3_lp9,
        try_cast("nivel_4_LP9" as double) as nivel_4_lp9,
        try_cast("nivel_5_LP9" as double) as nivel_5_lp9,
        try_cast("nivel_6_LP9" as double) as nivel_6_lp9,
        try_cast("nivel_7_LP9" as double) as nivel_7_lp9,
        try_cast("nivel_8_LP9" as double) as nivel_8_lp9,
        try_cast("nivel_0_MT9" as double) as nivel_0_mt9,
        try_cast("nivel_1_MT9" as double) as nivel_1_mt9,
        try_cast("nivel_2_MT9" as double) as nivel_2_mt9,
        try_cast("nivel_3_MT9" as double) as nivel_3_mt9,
        try_cast("nivel_4_MT9" as double) as nivel_4_mt9,
        try_cast("nivel_5_MT9" as double) as nivel_5_mt9,
        try_cast("nivel_6_MT9" as double) as nivel_6_mt9,
        try_cast("nivel_7_MT9" as double) as nivel_7_mt9,
        try_cast("nivel_8_MT9" as double) as nivel_8_mt9,
        try_cast("nivel_9_MT9" as double) as nivel_9_mt9,
        try_cast("nivel_0_LP12" as double) as nivel_0_lp12,
        try_cast("nivel_1_LP12" as double) as nivel_1_lp12,
        try_cast("nivel_2_LP12" as double) as nivel_2_lp12,
        try_cast("nivel_3_LP12" as double) as nivel_3_lp12,
        try_cast("nivel_4_LP12" as double) as nivel_4_lp12,
        try_cast("nivel_5_LP12" as double) as nivel_5_lp12,
        try_cast("nivel_6_LP12" as double) as nivel_6_lp12,
        try_cast("nivel_7_LP12" as double) as nivel_7_lp12,
        try_cast("nivel_8_LP12" as double) as nivel_8_lp12,
        try_cast("nivel_0_MT12" as double) as nivel_0_mt12,
        try_cast("nivel_1_MT12" as double) as nivel_1_mt12,
        try_cast("nivel_2_MT12" as double) as nivel_2_mt12,
        try_cast("nivel_3_MT12" as double) as nivel_3_mt12,
        try_cast("nivel_4_MT12" as double) as nivel_4_mt12,
        try_cast("nivel_5_MT12" as double) as nivel_5_mt12,
        try_cast("nivel_6_MT12" as double) as nivel_6_mt12,
        try_cast("nivel_7_MT12" as double) as nivel_7_mt12,
        try_cast("nivel_8_MT12" as double) as nivel_8_mt12,
        try_cast("nivel_9_MT12" as double) as nivel_9_mt12,
        try_cast("nivel_10_MT12" as double) as nivel_10_mt12,
        try_cast("nivel_0_LP13" as double) as nivel_0_lp13,
        try_cast("nivel_1_LP13" as double) as nivel_1_lp13,
        try_cast("nivel_2_LP13" as double) as nivel_2_lp13,
        try_cast("nivel_3_LP13" as double) as nivel_3_lp13,
        try_cast("nivel_4_LP13" as double) as nivel_4_lp13,
        try_cast("nivel_5_LP13" as double) as nivel_5_lp13,
        try_cast("nivel_6_LP13" as double) as nivel_6_lp13,
        try_cast("nivel_7_LP13" as double) as nivel_7_lp13,
        try_cast("nivel_8_LP13" as double) as nivel_8_lp13,
        try_cast("nivel_0_MT13" as double) as nivel_0_mt13,
        try_cast("nivel_1_MT13" as double) as nivel_1_mt13,
        try_cast("nivel_2_MT13" as double) as nivel_2_mt13,
        try_cast("nivel_3_MT13" as double) as nivel_3_mt13,
        try_cast("nivel_4_MT13" as double) as nivel_4_mt13,
        try_cast("nivel_5_MT13" as double) as nivel_5_mt13,
        try_cast("nivel_6_MT13" as double) as nivel_6_mt13,
        try_cast("nivel_7_MT13" as double) as nivel_7_mt13,
        try_cast("nivel_8_MT13" as double) as nivel_8_mt13,
        try_cast("nivel_9_MT13" as double) as nivel_9_mt13,
        try_cast("nivel_10_MT13" as double) as nivel_10_mt13,
        try_cast("nivel_0_LP14" as double) as nivel_0_lp14,
        try_cast("nivel_1_LP14" as double) as nivel_1_lp14,
        try_cast("nivel_2_LP14" as double) as nivel_2_lp14,
        try_cast("nivel_3_LP14" as double) as nivel_3_lp14,
        try_cast("nivel_4_LP14" as double) as nivel_4_lp14,
        try_cast("nivel_5_LP14" as double) as nivel_5_lp14,
        try_cast("nivel_6_LP14" as double) as nivel_6_lp14,
        try_cast("nivel_7_LP14" as double) as nivel_7_lp14,
        try_cast("nivel_8_LP14" as double) as nivel_8_lp14,
        try_cast("nivel_0_MT14" as double) as nivel_0_mt14,
        try_cast("nivel_1_MT14" as double) as nivel_1_mt14,
        try_cast("nivel_2_MT14" as double) as nivel_2_mt14,
        try_cast("nivel_3_MT14" as double) as nivel_3_mt14,
        try_cast("nivel_4_MT14" as double) as nivel_4_mt14,
        try_cast("nivel_5_MT14" as double) as nivel_5_mt14,
        try_cast("nivel_6_MT14" as double) as nivel_6_mt14,
        try_cast("nivel_7_MT14" as double) as nivel_7_mt14,
        try_cast("nivel_8_MT14" as double) as nivel_8_mt14,
        try_cast("nivel_9_MT14" as double) as nivel_9_mt14,
        try_cast("nivel_10_MT14" as double) as nivel_10_mt14
    from {{ source('raw_saeb_2023', 'saeb_resultados_municipios_2023') }}
    where try_cast("ANO_SAEB" as integer) = 2023
)

select * from saeb_2019
union all
select * from saeb_2021_2023
